# Generated by Django 4.1.2 on 2022-10-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_message_content'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created'], name='core_messag_created_cea725_idx'),
        ),
    ]
